### ISSUE TITLE
Linux desktop browsers cause an exception

### ISSUE THREAD

**Issue by tornewuff** [pupunzi/jquery.mb.browser#8]
The code for handling Linux useragents does this: 

```javascript
		if (/Linux/.test(nAgt) && /Linux/.test(nAgt))
			os.version = /Android ([\.\_\d]+)/.exec(nAgt)[1];
```

This doesn't work for desktop Linux browsers, which aren't Android and so the Android version won't be present. Was it supposed to be testing for /Linux/ and /Android/ in the if condition instead?

**Comment by pupunzi** [comment]
hi,
that issue should has already be fixed on the latest release.
